import { CarGroupsEnum } from "../app/enum/car-groups.enum";
import { CarModelEnum } from "../app/enum/car-model.enum";
import { TrackNameEnum } from "../app/enum/track-name.enum";

/**
 * Not i18n labels, but actual labels valid for every language
 */
export const LABELS = {
    CAR_GROUP: {
        [CarGroupsEnum.FREE_FOR_ALL]: 'Free for All',
        [CarGroupsEnum.GT3]: 'GT3',
        [CarGroupsEnum.GT4]: 'GT4',
        [CarGroupsEnum.GT2]: 'GT2',
        [CarGroupsEnum.GTC]: 'GTC',
        [CarGroupsEnum.TCX]: 'TCX',
    },
    CAR_MODEL: {
        [CarModelEnum.PORSCHE_991_GT3_R]: 'Porsche 991 GT3 R',
        [CarModelEnum.MERCEDES_AMG_GT3]: 'Mercedes-AMG GT3',
        [CarModelEnum.FERRARI_488_GT3]: 'Ferrari 488 GT3',
        [CarModelEnum.AUDI_R8_LMS]: 'Audi R8 LMS',
        [CarModelEnum.LAMBORGHINI_HURACAN_GT3]: 'Lamborghini Huracán GT3',
        [CarModelEnum.MCLAREN_650S_GT3]: 'McLaren 650S GT3',
        [CarModelEnum.NISSAN_GTR_NISMO_GT3_2018]: 'Nissan GT-R Nismo GT3 2018',
        [CarModelEnum.BMW_M6_GT3]: 'BMW M6 GT3',
        [CarModelEnum.BENTLEY_CONTINENTAL_GT3_2018]: 'Bentley Continental GT3 2018',
        [CarModelEnum.PORSCHE_991II_GT3_CUP]: 'Porsche 991 II GT3 Cup',
        [CarModelEnum.NISSAN_GTR_NISMO_GT3_2017]: 'Nissan GT-R Nismo GT3 2017',
        [CarModelEnum.BENTLEY_CONTINENTAL_GT3_2016]: 'Bentley Continental GT3 2016',
        [CarModelEnum.ASTON_MARTIN_V12_VANTAGE_GT3]: 'Aston Martin V12 Vantage GT3',
        [CarModelEnum.LAMBORGHINI_GALLARDO_REX]: 'Lamborghini Gallardo R-EX',
        [CarModelEnum.JAGUAR_G3]: 'Jaguar G3',
        [CarModelEnum.LEXUS_RCF_GT3]: 'Lexus RC F GT3',
        [CarModelEnum.LAMBORGHINI_HURACAN_EVO_2019]: 'Lamborghini Huracán Evo 2019',
        [CarModelEnum.HONDA_NSX_GT3]: 'Honda NSX GT3',
        [CarModelEnum.LAMBORGHINI_HURACAN_SUPERTROFEO]: 'Lamborghini Huracán SuperTrofeo',
        [CarModelEnum.AUDI_R8_LMS_EVO_2019]: 'Audi R8 LMS Evo 2019',
        [CarModelEnum.AMR_V8_VANTAGE_2019]: 'AMR V8 Vantage 2019',
        [CarModelEnum.HONDA_NSX_EVO_2019]: 'Honda NSX Evo 2019',
        [CarModelEnum.MCLAREN_720S_GT3_2019]: 'McLaren 720S GT3 2019',
        [CarModelEnum.PORSCHE_911II_GT3_R_2019]: 'Porsche 911 II GT3 R 2019',
        [CarModelEnum.FERRARI_488_GT3_EVO_2020]: 'Ferrari 488 GT3 Evo 2020',
        [CarModelEnum.MERCEDES_AMG_GT3_2020]: 'Mercedes-AMG GT3 2020',
        [CarModelEnum.FERRARI_488_CHALLENGE_EVO]: 'Ferrari 488 Challenge Evo',
        [CarModelEnum.BMW_M2_CS_RACING]: 'BMW M2 CS Racing',
        [CarModelEnum.PORSCHE_911_GT3_CUP_992]: 'Porsche 911 GT3 Cup (Type 992)',
        [CarModelEnum.LAMBORGHINI_HURACAN_SUPERTROFEO_EVO2]: 'Lamborghini Huracán Super Trofeo EVO2',
        [CarModelEnum.BMW_M4_GT3]: 'BMW M4 GT3',
        [CarModelEnum.AUDI_R8_LMS_GT3_EVO_II]: 'Audi R8 LMS GT3 Evo II',
        [CarModelEnum.FERRARI_296_GT3]: 'Ferrari 296 GT3',
        [CarModelEnum.LAMBORGHINI_HURACAN_EVO2]: 'Lamborghini Huracán Evo2',
        [CarModelEnum.PORSCHE_992_GT3_R]: 'Porsche 992 GT3 R',
        [CarModelEnum.MCLAREN_720S_GT3_EVO_2023]: 'McLaren 720S GT3 Evo 2023',
        [CarModelEnum.FORD_MUSTANG_GT3]: 'Ford Mustang GT3',
        [CarModelEnum.ALPINE_A110_GT4]: 'Alpine A110 GT4',
        [CarModelEnum.AMR_V8_VANTAGE_GT4]: 'AMR V8 Vantage GT4',
        [CarModelEnum.AUDI_R8_LMS_GT4]: 'Audi R8 LMS GT4',
        [CarModelEnum.BMW_M4_GT4]: 'BMW M4 GT4',
        [CarModelEnum.CHEVROLET_CAMARO_GT4]: 'Chevrolet Camaro GT4',
        [CarModelEnum.GINETTA_G55_GT4]: 'Ginetta G55 GT4',
        [CarModelEnum.KTM_XBOW_GT4]: 'KTM X-Bow GT4',
        [CarModelEnum.MASERATI_MC_GT4]: 'Maserati MC GT4',
        [CarModelEnum.MCLAREN_570S_GT4]: 'McLaren 570S GT4',
        [CarModelEnum.MERCEDES_AMG_GT4]: 'Mercedes-AMG GT4',
        [CarModelEnum.PORSCHE_718_CAYMAN_GT4]: 'Porsche 718 Cayman GT4',
        [CarModelEnum.AUDI_R8_LMS_GT2]: 'Audi R8 LMS GT2',
        [CarModelEnum.KTM_XBOW_GT2]: 'KTM X-Bow GT2',
        [CarModelEnum.MASERATI_MC20_GT2]: 'Maserati MC20 GT2',
        [CarModelEnum.MERCEDES_AMG_GT2]: 'Mercedes AMG GT2',
        [CarModelEnum.PORSCHE_911_GT2_RS_CS_EVO]: 'Porsche 911 GT2 RS CS Evo',
        [CarModelEnum.PORSCHE_935]: 'Porsche 935',
    },
    TRACK_NAME: {
        [TrackNameEnum.MONZA]: 'Monza',
        [TrackNameEnum.ZOLDER]: 'Zolder',
        [TrackNameEnum.BRANDS_HATCH]: 'Brands Hatch',
        [TrackNameEnum.SILVERSTONE]: 'Silverstone',
        [TrackNameEnum.PAUL_RICARD]: 'Paul Ricard',
        [TrackNameEnum.MISANO]: 'Misano',
        [TrackNameEnum.SPA]: 'Spa-Francorchamps',
        [TrackNameEnum.NURBURGRING]: 'Nürburgring',
        [TrackNameEnum.BARCELONA]: 'Circuit de Barcelona-Catalunya',
        [TrackNameEnum.HUNGARORING]: 'Hungaroring',
        [TrackNameEnum.ZANDVOORT]: 'Circuit Zandvoort',
        [TrackNameEnum.KYALAMI]: 'Kyalami',
        [TrackNameEnum.MOUNT_PANORAMA]: 'Mount Panorama',
        [TrackNameEnum.SUZUKA]: 'Suzuka',
        [TrackNameEnum.LAGUNA_SECA]: 'Laguna Seca',
        [TrackNameEnum.IMOLA]: 'Imola',
        [TrackNameEnum.OULTON_PARK]: 'Oulton Park',
        [TrackNameEnum.DONINGTON]: 'Donington Park',
        [TrackNameEnum.SNETTERTON]: 'Snetterton',
        [TrackNameEnum.COTA]: 'Circuit of the Americas',
        [TrackNameEnum.INDIANAPOLIS]: 'Indianapolis Motor Speedway',
        [TrackNameEnum.WATKINS_GLEN]: 'Watkins Glen',
        [TrackNameEnum.VALENCIA]: 'Circuit Ricardo Tormo',
        [TrackNameEnum.NURBURGRING_24H]: 'Nürburgring 24h',
    },
    APP: {
        GITHUB: {
            REPOSITORY: 'Github Repository'
        },
        LINKEDIN: {
            LINKEDIN: 'LinkedIn'
        }
    }
};
