// Values to be put in JSON configuration files
export enum TrackNameEnum {
  MONZA = "monza",
  ZOLDER = "zolder",
  BRANDS_HATCH = "brands_hatch",
  SILVERSTONE = "silverstone",
  PAUL_RICARD = "paul_ricard",
  MISANO = "misano",
  SPA = "spa",
  NURBURGRING = "nurburgring",
  BARCELONA = "barcelona",
  HUNGARORING = "hungaroring",
  ZANDVOORT = "zandvoort",
  KYALAMI = "kyalami",
  MOUNT_PANORAMA = "mount_panorama",
  SUZUKA = "suzuka",
  LAGUNA_SECA = "laguna_seca",
  IMOLA = "imola",
  OULTON_PARK = "oulton_park",
  DONINGTON = "donington",
  SNETTERTON = "snetterton",
  COTA = "cota",
  INDIANAPOLIS = "indianapolis",
  WATKINS_GLEN = "watkins_glen",
  VALENCIA = "valencia",
  NURBURGRING_24H = "nurburgring_24h",
}
